apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: hello-java
  newName: alexandrejonathas/estudos-gitops
  newTag: 814f32c11d32c212ee1dd171bc7469171b810e0d
