apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: hello-java
  newName: alexandrejonathas/estudos-gitops
  newTag: 98a55e74cc01becf390ed9bd1cb914aea879e617
