apiVersion: v1
kind: Service
metadata:
  name: hello-java-service
spec:
  selector:
    app: hello-java
  ports:
  - nodePort: 30001
    port: 9090
    targetPort: 8080
    protocol: TCP
  type: NodePort
