name: ci app java

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          
      # - name: Build with Maven
      #   run: |
      #     cd app && mvn clean package --file pom.xml -DskipTests && cd ..

      - name: Push image to docker
        uses: docker/build-push-actions@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME}}/estudos-gitops
          tags: ${{ github.sha }}, latest



