name: ci app java

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image
        run: cd ./app && docker build . --file Dockerfile --tag $DOCKER_USERNAME/estudos-gitops:$(date +%s)

      - name: Push image to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/estudos-gitops



