name: ci app java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build with Maven
      run: |
        cd app && mvn clean package --file pom.xml -DskipTests && cd ..


